openapi: 3.0.0
info:
  title: ExpenseMate API
  description: API documentation for ExpenseMate application
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local server

components:
  schemas:
    Budget:
      type: object
      properties:
        _id:
          type: string
        user:
          type: string
        name:
          type: string
        totalAmount:
          type: number
        categories:
          type: array
          items:
            type: object
            properties:
              category:
                type: string
              amount:
                type: number
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - name
        - totalAmount
        - categories
        - startDate
        - endDate
    Error:
      type: object
      properties:
        message:
          type: string
        stack:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /budget:
    post:
      summary: Add new budget
      tags: [Budget]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                totalAmount:
                  type: number
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      category:
                        type: string
                      amount:
                        type: number
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
              required:
                - name
                - totalAmount
                - categories
                - startDate
                - endDate
      responses:
        '201':
          description: Budget created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Budget'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get all budgets
      tags:
        - Budget
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: date
          description: Start date for filtering budgets
        - in: query
          name: endDate
          schema:
            type: string
            format: date
          description: End date for filtering budgets
        - in: query
          name: category
          schema:
            type: string
          description: Category for filtering budgets
        - in: query
          name: tag
          schema:
            type: string
            enum: [one-time, monthly, recurring]
          description: Tag for filtering budgets
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Budget'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /budget/{id}:
    put:
      summary: Update budget
      tags: [Budget]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                totalAmount:
                  type: number
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      category:
                        type: string
                      amount:
                        type: number
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
      responses:
        '200':
          description: Budget updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Budget'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Budget not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete budget
      tags: [Budget]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Budget removed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Budget not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

