openapi: 3.0.0
info:
  title: ExpenseMate API
  description: API documentation for ExpenseMate application
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local server

components:
  schemas:
    Expense:
      type: object
      properties:
        _id:
          type: string
        user:
          type: string
        date:
          type: string
          format: date
        category:
          type: string
        amount:
          type: number
        tag:
          type: string
        notes:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - date
        - category
        - amount
        - tag
    Error:
      type: object
      properties:
        message:
          type: string
        stack:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /expense:
    post:
      summary: Add new expense
      tags: [Expenses]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                category:
                  type: string
                amount:
                  type: number
                tag:
                  type: string
                notes:
                  type: string
              required:
                - date
                - category
                - amount
                - tag
      responses:
        '201':
          description: Expense created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get all expenses
      tags:
        - Expenses
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: date
          description: Start date for filtering expenses
        - in: query
          name: endDate
          schema:
            type: string
            format: date
          description: End date for filtering expenses
        - in: query
          name: category
          schema:
            type: string
          description: Category for filtering expenses
        - in: query
          name: tag
          schema:
            type: string
            enum: [one-time, monthly, recurring]
          description: Tag for filtering expenses
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Expense'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /expense/{id}:
    put:
      summary: Update expense
      tags: [Expenses]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                category:
                  type: string
                amount:
                  type: number
                tag:
                  type: string
                notes:
                  type: string
      responses:
        '200':
          description: Expense updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Expense not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete expense
      tags: [Expenses]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Expense removed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Expense not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

